### ISSUE TITLE
Make parameters configurable

### ISSUE THREAD

**Issue by alytarik** [JohnSnowLabs/langtest#857]
Explore and convert hardcoded thresholds/parameters to config based ones.

Current Findings:
- CrowS-Pairs
    - diff_treshold
    - filter_treshold
- Wino-Bias
    - diff_treshold

**Comment by ArshaanNazir** [comment]
Kindly look for other cases as well. Like Wino-bias also has hardcoded ones ( because we came up with those after manual review from annotators as well). However if user wants to change them according to his choice, it should be possible. Can we do that for the sentence transformers as well, where in user can choose and use those only.
